import type {
  InteractionManifestEntry,
} from "../../interaction-manifest/schema";

const browsers = [
  "chromium",
  "firefox",
  "webkit",
  "chromium-enterprise",
  "android-chromium",
  "iphone-webkit",
  "tablet-chromium",
] as const;
const viewports = [
  "360x800",
  "390x844",
  "768x1024",
  "1024x768",
  "1280x800",
  "1440x900",
  "1920x1080",
  "2560x1440",
  "200%",
] as const;
const promotionTestIds = [
  "e2e.research-lab.complete-promotion-lifecycle",
] as const;
const actionTestIds = [
  "e2e.research-lab.complete-promotion-lifecycle",
  "e2e.research-lab.promotion-action-matrix",
] as const;
const reliabilityTestIds = [
  "e2e.research-lab.promotion-reliability",
] as const;
const responseLossTestIds = [
  "e2e.research-lab.promotion-response-loss",
] as const;
const reconciliationTestIds = [
  ...reliabilityTestIds,
  ...responseLossTestIds,
] as const;
const humanReviewVisual = [
  "visual.research.promotion-human-review.chromium-1440",
] as const;
const canaryVisual = [
  "visual.research.promotion-bounded-canary.chromium-1440",
] as const;
const rollbackVisual = [
  "visual.research.promotion-forward-rollback.chromium-1440",
] as const;
const reconciliationVisual = [
  "visual.research.promotion-reconciliation.chromium-1440",
] as const;
const route = "/learning?view=research";

/**
 * Staged separately while the shared manifest is frozen by the release owner.
 * These entries are intentionally not loaded by the manifest auditor until
 * that owner performs the coordinated manifest/count/receipt update.
 */
export const RESEARCH_PROMOTION_MANIFEST_STAGING:
readonly InteractionManifestEntry[] = [
  {
    id: "research.promotion-history",
    route,
    surface: "Research Lab — immutable promotion history",
    requiredState: "A durable candidate promotion lifecycle is present",
    controlId: "research-promotion-history",
    accessible: {
      locator: "native-summary",
      name: "Immutable transition history",
      match: "exact",
    },
    controlType: "immutable-promotion-ledger-disclosure",
    options: ["Open or close the signed lifecycle transition history"],
    keyboardAction: "Focus the disclosure and press Enter",
    pointerAction: "Click Immutable transition history",
    expectedStateTransition: "Reveal actor, state, receipt, hard-gate, deployment, and evidence bindings in sequence",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Absent until the lifecycle projection loads",
      disabled: "Never disabled for a returned lifecycle",
      error: "No history is fabricated when lifecycle validation fails",
    },
    classification: "read-only",
    screenshotsRequired: humanReviewVisual,
    browsers,
    viewports,
    testIds: promotionTestIds,
  },
  {
    id: "research.promotion-rationale",
    route,
    surface: "Research Lab — human promotion decision",
    requiredState: "At least one human action is valid for the candidate",
    controlId: "research-promotion-rationale",
    accessible: {
      role: "textbox",
      name: "Decision rationale",
      match: "exact",
    },
    controlType: "attributable-promotion-rationale",
    options: ["Record a readable rationale for the represented transition"],
    keyboardAction: "Focus with Tab and enter the rationale",
    pointerAction: "Click and enter the rationale",
    expectedStateTransition: "Stage a rationale without changing canonical lifecycle state",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Retained while the represented transition is pending",
      disabled: "Absent when no human action is valid",
      error: "A rationale shorter than three characters keeps actions disabled",
    },
    classification: "reversible",
    screenshotsRequired: humanReviewVisual,
    browsers,
    viewports,
    testIds: promotionTestIds,
  },
  {
    id: "research.promotion-evidence",
    route,
    surface: "Research Lab — human promotion decision",
    requiredState: "At least one human action is valid for the candidate",
    controlId: "research-promotion-evidence",
    accessible: {
      role: "textbox",
      name: "Evidence or receipt references",
      match: "exact",
    },
    controlType: "promotion-evidence-reference-list",
    options: ["Record comma- or newline-separated stable evidence and receipt IDs"],
    keyboardAction: "Focus with Tab and enter stable references",
    pointerAction: "Click and enter stable references",
    expectedStateTransition: "Stage immutable evidence bindings without changing lifecycle state",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Retained while the represented transition is pending",
      disabled: "Absent when no human action is valid",
      error: "An empty reference list keeps actions disabled",
    },
    classification: "reversible",
    screenshotsRequired: humanReviewVisual,
    browsers,
    viewports,
    testIds: promotionTestIds,
  },
  {
    id: "research.promotion-canary-bounds",
    route,
    surface: "Research Lab — bounded canary configuration",
    requiredState: "The candidate passed shadow and the human reviewer approved canary",
    controlId: "research-promotion-canary-bounds",
    accessible: {
      role: "spinbutton",
      name: "^(?:Maximum missions|Maximum minutes)$",
      match: "regex",
    },
    controlType: "bounded-canary-limit-family",
    options: ["Set maximum missions", "Set maximum minutes"],
    keyboardAction: "Focus each field and enter a value within its represented bound",
    pointerAction: "Click each field and enter a value within its represented bound",
    expectedStateTransition: "Stage explicit canary mission and time limits",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Retained while canary start is pending",
      disabled: "Absent outside canary_ready",
      error: "Values outside one to ten missions or one to 1,440 minutes keep start disabled",
    },
    classification: "reversible",
    screenshotsRequired: canaryVisual,
    browsers,
    viewports,
    testIds: promotionTestIds,
  },
  {
    id: "research.promotion-rollback-target",
    route,
    surface: "Research Lab — forward rollback target",
    requiredState: "A current candidate and a different previously verified campaign strategy exist",
    controlId: "research-promotion-rollback-target",
    accessible: {
      role: "radio",
      name: "^research-promotion-.+-strategy-prior.+$",
      match: "regex",
    },
    controlType: "verified-strategy-forward-selection",
    options: ["Choose a different previously verified strategy"],
    keyboardAction: "Focus the verified target and press Space",
    pointerAction: "Click the verified target",
    expectedStateTransition: "Select an existing immutable strategy pointer without copying a bundle or database state",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Absent until rollback targets load",
      disabled: "Rollback is disabled when no different verified target exists",
      error: "A missing or stale target is rejected by server verification",
    },
    classification: "reversible",
    screenshotsRequired: rollbackVisual,
    browsers,
    viewports,
    testIds: promotionTestIds,
  },
  {
    id: "research.promotion-actions",
    route,
    surface: "Research Lab — human-owned promotion path",
    requiredState: "A candidate is at a lifecycle state with represented human actions",
    controlId: "research-promotion-actions",
    accessible: {
      role: "button",
      name: "^(?:Approve for isolated shadow|Reject after human review|Start isolated shadow|Approve bounded canary|Start bounded canary|Verify strategy|Reject candidate|Mark strategy stale|Supersede strategy|Roll back by forward activation)$",
      match: "regex",
    },
    controlType: "optimistic-idempotent-promotion-action-family",
    options: [
      "Approve for isolated shadow",
      "Reject after human review",
      "Start isolated shadow",
      "Approve bounded canary",
      "Start bounded canary",
      "Verify strategy",
      "Reject candidate",
      "Mark strategy stale",
      "Supersede strategy",
      "Roll back by forward activation",
    ],
    keyboardAction: "Focus the currently represented action and press Enter or Space",
    pointerAction: "Click the currently represented action",
    expectedStateTransition: "Append one validated lifecycle transition with human actor, evidence, receipt, and optimistic-version bindings",
    expectedApiOrEventSideEffect: "POST /api/v2/research/experiments/:experimentId/promotion with a unique Idempotency-Key; shadow has no live effect, canary is bounded, verification creates no production deployment, and rollback appends a forward activation",
    states: {
      loading: "The selected action names progress and all actions are disabled",
      disabled: "Disabled until rationale and evidence are valid and required canary or rollback inputs are complete",
      error: "The frozen intent is retained for exact retry or lifecycle reconciliation",
    },
    classification: "destructive",
    screenshotsRequired: [
      ...humanReviewVisual,
      ...canaryVisual,
      ...rollbackVisual,
    ],
    browsers,
    viewports,
    testIds: actionTestIds,
  },
  {
    id: "research.promotion-refresh",
    route,
    surface: "Research Lab — promotion conflict reconciliation",
    requiredState: "A non-retryable lifecycle-version conflict is represented",
    controlId: "research-promotion-refresh",
    accessible: {
      role: "button",
      name: "Refresh lifecycle state",
      match: "exact",
    },
    controlType: "promotion-optimistic-conflict-reconciliation",
    options: ["Refresh the current lifecycle without replaying the stale mutation"],
    keyboardAction: "Focus with Tab and press Enter",
    pointerAction: "Click Refresh lifecycle state",
    expectedStateTransition: "Read the current lifecycle while retaining the human rationale for renewed review",
    expectedApiOrEventSideEffect: "GET /api/v2/research only",
    states: {
      loading: "Named Refreshing Research Lab state and disabled",
      disabled: "Absent for retryable errors and successful transitions",
      error: "The original conflict and refresh error remain visible without a mutation replay",
    },
    classification: "read-only",
    screenshotsRequired: reconciliationVisual,
    browsers,
    viewports,
    testIds: reliabilityTestIds,
  },
  {
    id: "research.promotion-uncertain-refresh",
    route,
    surface: "Research Lab — response-loss reconciliation",
    requiredState: "A promotion response was unusable and the original decision outcome is uncertain",
    controlId: "research-promotion-uncertain-refresh",
    accessible: {
      role: "button",
      name: "Refresh lifecycle state",
      match: "exact",
    },
    controlType: "promotion-response-loss-reconciliation",
    options: [
      "Refresh canonical lifecycle after an unusable mutation response",
    ],
    keyboardAction: "Focus Refresh lifecycle state and press Enter",
    pointerAction: "Click Refresh lifecycle state",
    expectedStateTransition: "Classify the exact next canonical transition as this reviewer, a different reviewer, or unchanged before clearing or replaying retained intent",
    expectedApiOrEventSideEffect: "GET /api/v2/research only; the uncertain mutation is never replayed by refresh",
    states: {
      loading: "Named Refreshing Research Lab state and disabled",
      disabled: "Absent when no response-uncertain intent exists",
      error: "A refresh failure preserves the frozen intent and original uncertainty",
    },
    classification: "read-only",
    screenshotsRequired: reconciliationVisual,
    browsers,
    viewports,
    testIds: responseLossTestIds,
  },
  {
    id: "research.promotion-mutation-retry",
    route,
    surface: "Research Lab — retryable promotion persistence failure",
    requiredState: "A real SQLite write reservation returned retryable research_store_busy for a human promotion transition",
    controlId: "research-promotion-mutation-retry",
    accessible: {
      role: "button",
      name: "Try again",
      match: "exact",
    },
    controlType: "idempotent-promotion-mutation-retry",
    options: [
      "Retry the exact promotion intent with its original idempotency key",
    ],
    keyboardAction: "Focus Try again and press Enter",
    pointerAction: "Click Try again",
    expectedStateTransition: "Resubmit the frozen lifecycle version, action, rationale, evidence, bounds, target, and key exactly once",
    expectedApiOrEventSideEffect: "POST the exact original promotion body with the exact original Idempotency-Key",
    states: {
      loading: "Removed while the exact retry is pending",
      disabled: "Absent for non-retryable promotion failures",
      error: "Another retryable failure retains the frozen intent and key",
    },
    classification: "reversible",
    screenshotsRequired: reconciliationVisual,
    browsers,
    viewports,
    testIds: reliabilityTestIds,
  },
  {
    id: "research.promotion-discard-retained-decision",
    route,
    surface: "Research Lab — retained promotion decision",
    requiredState: "A retryable or response-uncertain promotion decision is retained in the actor-scoped tab session",
    controlId: "research-promotion-discard-retained-decision",
    accessible: {
      role: "button",
      name: "Discard retained decision",
      match: "exact",
    },
    controlType: "promotion-retry-intent-discard",
    options: ["Discard the retained decision before reviewing a new one"],
    keyboardAction: "Focus Discard retained decision and press Enter",
    pointerAction: "Click Discard retained decision",
    expectedStateTransition: "Remove only the exact actor-and-experiment retry record and require a newly reviewed decision",
    expectedApiOrEventSideEffect: null,
    states: {
      loading: "Disabled only while the represented retry is dispatching",
      disabled: "Absent when no retained retry intent exists",
      error: "Storage cleanup failure remains fail-closed and cannot replay a different body",
    },
    classification: "reversible",
    screenshotsRequired: reconciliationVisual,
    browsers,
    viewports,
    testIds: reconciliationTestIds,
  },
] as const;
