import type { MemoryNodeType } from "../memory";
import {
  BRAIN_LIFECYCLE_HOOKS,
  type BrainLifecycleHook,
  type BrainLifecycleHookDefinition,
} from "./types";

function definition(
  value: BrainLifecycleHookDefinition,
): BrainLifecycleHookDefinition {
  return Object.freeze({
    ...value,
    allowedNodeTypes: Object.freeze([...value.allowedNodeTypes]),
  });
}

const REGISTRY: Readonly<Record<BrainLifecycleHook, BrainLifecycleHookDefinition>> = Object.freeze({
  intake: definition({
    hook: "intake",
    label: "Mission intake",
    purpose: "Retrieve confirmed collaboration preferences, related mission knowledge, and verified lessons for mission intake.",
    requiresRun: false,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["preference", "mission", "target", "lesson", "failure", "recovery", "source"],
    maximumSensitivity: "private",
    defaultContextBudget: 2_000,
    maximumContextBudget: 4_000,
    defaultLimit: 8,
    maximumLimit: 16,
    graphDepth: 1,
  }),
  planning: definition({
    hook: "planning",
    label: "Mission planning",
    purpose: "Retrieve the smallest verified strategy, specialist, evidence, and prior-outcome context needed for planning.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: [
      "preference", "mission", "run", "plan", "agent", "tool", "mcp_capability",
      "technique", "procedure", "target", "asset", "failure", "recovery", "lesson", "report",
    ],
    maximumSensitivity: "private",
    defaultContextBudget: 6_000,
    maximumContextBudget: 8_000,
    defaultLimit: 12,
    maximumLimit: 24,
    graphDepth: 1,
  }),
  assignment_acceptance: definition({
    hook: "assignment_acceptance",
    label: "Assignment acceptance",
    purpose: "Retrieve bounded capability, dependency, and prior-failure context before a specialist accepts an assignment.",
    requiresRun: true,
    requiresStep: true,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["step", "agent", "tool", "mcp_capability", "technique", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 2_500,
    maximumContextBudget: 4_000,
    defaultLimit: 8,
    maximumLimit: 16,
    graphDepth: 1,
  }),
  tool_selection: definition({
    hook: "tool_selection",
    label: "Tool selection",
    purpose: "Retrieve scoped tool compatibility, prerequisites, and failure memory before selecting a tool.",
    requiresRun: true,
    requiresStep: true,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["step", "tool", "mcp_capability", "technique", "procedure", "target", "asset", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 2_500,
    maximumContextBudget: 4_000,
    defaultLimit: 8,
    maximumLimit: 16,
    graphDepth: 1,
  }),
  attack_attempt: definition({
    hook: "attack_attempt",
    label: "Attack attempt",
    purpose: "Retrieve the exact target, technique, evidence, and failed-attempt context before a represented attack attempt.",
    requiresRun: true,
    requiresStep: true,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["step", "tool", "technique", "procedure", "target", "asset", "evidence", "finding", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 3_000,
    maximumContextBudget: 5_000,
    defaultLimit: 10,
    maximumLimit: 20,
    graphDepth: 1,
  }),
  phase_transition: definition({
    hook: "phase_transition",
    label: "Phase transition",
    purpose: "Refresh mission, evidence, preference, and failure context after a material phase or hypothesis change.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["preference", "mission", "run", "plan", "phase", "step", "target", "asset", "evidence", "finding", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 4_000,
    maximumContextBudget: 8_000,
    defaultLimit: 10,
    maximumLimit: 24,
    graphDepth: 1,
  }),
  failure: definition({
    hook: "failure",
    label: "Failure handling",
    purpose: "Retrieve related failed attempts and verified recoveries before retrying, reassigning, or stopping.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["step", "agent", "tool", "mcp_capability", "technique", "procedure", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 5_000,
    maximumContextBudget: 8_000,
    defaultLimit: 12,
    maximumLimit: 24,
    graphDepth: 2,
  }),
  replan: definition({
    hook: "replan",
    label: "Replanning",
    purpose: "Retrieve materially different verified strategies and failed-attempt constraints before creating a new plan version.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["plan", "step", "agent", "tool", "mcp_capability", "technique", "procedure", "target", "asset", "evidence", "finding", "failure", "recovery", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 5_000,
    maximumContextBudget: 8_000,
    defaultLimit: 12,
    maximumLimit: 24,
    graphDepth: 2,
  }),
  finding_validation: definition({
    hook: "finding_validation",
    label: "Finding validation",
    purpose: "Retrieve scoped evidence, provenance, and comparable findings before validating a conclusion.",
    requiresRun: true,
    requiresStep: true,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["step", "target", "asset", "technique", "procedure", "evidence", "finding", "artifact", "lesson"],
    maximumSensitivity: "private",
    defaultContextBudget: 4_000,
    maximumContextBudget: 6_000,
    defaultLimit: 12,
    maximumLimit: 24,
    graphDepth: 1,
  }),
  reporting: definition({
    hook: "reporting",
    label: "Reporting",
    purpose: "Retrieve confirmed report preferences and evidence-linked mission outcomes for a traceable report.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["preference", "mission", "run", "plan", "evidence", "finding", "artifact", "evaluation", "lesson", "report", "source"],
    maximumSensitivity: "private",
    defaultContextBudget: 6_000,
    maximumContextBudget: 8_000,
    defaultLimit: 16,
    maximumLimit: 32,
    graphDepth: 1,
  }),
  lesson_proposal: definition({
    hook: "lesson_proposal",
    label: "Lesson proposal",
    purpose: "Retrieve related lessons, counterexamples, failures, and evaluations before proposing a reviewable lesson.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["mission", "run", "evidence", "finding", "failure", "recovery", "evaluation", "lesson", "source"],
    maximumSensitivity: "private",
    defaultContextBudget: 4_000,
    maximumContextBudget: 6_000,
    defaultLimit: 12,
    maximumLimit: 24,
    graphDepth: 2,
  }),
  evaluation: definition({
    hook: "evaluation",
    label: "Run evaluation",
    purpose: "Retrieve the run's plan, evidence, failures, lessons, and comparable evaluations for evidence-linked scoring.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["mission", "run", "plan", "step", "evidence", "finding", "failure", "recovery", "evaluation", "lesson", "report"],
    maximumSensitivity: "private",
    defaultContextBudget: 5_000,
    maximumContextBudget: 8_000,
    defaultLimit: 16,
    maximumLimit: 32,
    graphDepth: 1,
  }),
  closeout: definition({
    hook: "closeout",
    label: "Mission closeout",
    purpose: "Retrieve the mission cluster needed to preserve outcomes, failures, recoveries, reports, and proposed learning.",
    requiresRun: true,
    requiresStep: false,
    allowGlobalWhenExplicit: true,
    allowedNodeTypes: ["preference", "mission", "run", "plan", "phase", "step", "agent", "target", "asset", "decision", "evidence", "finding", "artifact", "failure", "recovery", "evaluation", "lesson", "report", "source"],
    maximumSensitivity: "private",
    defaultContextBudget: 5_000,
    maximumContextBudget: 8_000,
    defaultLimit: 20,
    maximumLimit: 40,
    graphDepth: 1,
  }),
});

// Compile-time guard: every current memory type in each definition is a
// canonical MemoryNodeType, rather than a runtime-only string registry.
const _typedNodeTypes: readonly MemoryNodeType[] = BRAIN_LIFECYCLE_HOOKS
  .flatMap((hook) => REGISTRY[hook].allowedNodeTypes);
void _typedNodeTypes;

export function brainLifecycleHookDefinition(
  hook: BrainLifecycleHook,
): BrainLifecycleHookDefinition {
  return REGISTRY[hook];
}

export function listBrainLifecycleHookDefinitions(): readonly BrainLifecycleHookDefinition[] {
  return BRAIN_LIFECYCLE_HOOKS.map((hook) => REGISTRY[hook]);
}
