import { type FormEvent, useState } from "react";
import { AppLink } from "../../app/router/navigation";
import { operationsApi } from "../../data/api/operations";
import { useQuery } from "../../data/cache/QueryProvider";
import type { LessonRecord } from "../../domain/types/operations";
import { Button, Card, ErrorPanel, LoadingPanel, PageHeader, StatusPill } from "../../design-system/components/Primitives";
import { CursorControls, FilterForm, formatTime, JsonDetails, KeyValueGrid, percent, QueryBoundary, SelectFilter, StreamState, SurfaceTabs, useActionState, useUrlFilters } from "../runs/OperationalSurface";
import ResearchLabPage from "./ResearchLabPage";

type View = "research" | "lessons" | "evaluations" | "usage";
export default function LearningPage({ selectedLessonId }: { selectedLessonId?: string }) {
  const filters = useUrlFilters({ view: "lessons", limit: "25" });
  const view = (["research", "lessons", "evaluations", "usage"].includes(filters.values.view) ? filters.values.view : "lessons") as View;
  return <div className="os-page"><PageHeader eyebrow="Evidence-gated improvement" title="Learning Lab" description="Run evaluations, independently reviewed lessons, and measured reuse—never silent self-modification." actions={<StreamState />} />
    <SurfaceTabs current={view} items={[{ id: "research", label: "Research Lab", onSelect: () => filters.set({ view: "research" }) }, { id: "lessons", label: "Lessons", onSelect: () => filters.set({ view: "lessons" }) }, { id: "evaluations", label: "Evaluations", onSelect: () => filters.set({ view: "evaluations" }) }, { id: "usage", label: "Usage & impact", onSelect: () => filters.set({ view: "usage" }) }]} />
    {view === "research" && <ResearchLabPage />}{view === "lessons" && <Lessons filters={filters} selectedId={selectedLessonId} />}{view === "evaluations" && <Evaluations filters={filters} />}{view === "usage" && <Usage filters={filters} />}
  </div>;
}

function Lessons({ filters, selectedId }: { filters: ReturnType<typeof useUrlFilters>; selectedId?: string }) {
  const list = useQuery(`lessons:${filters.key}`, (signal) => operationsApi.lessons(filters.values, signal));
  const detail = useQuery(`lesson:${selectedId ?? "none"}`, (signal) => selectedId ? operationsApi.lesson(selectedId, signal) : Promise.resolve(undefined), { staleTime: 0 });
  return <><FilterForm filters={filters}><SelectFilter filters={filters} name="status" label="State" options={["proposed", "under_review", "verified", "rejected", "stale", "superseded"].map((value) => ({ value, label: value }))} /></FilterForm><div className="os-master-detail"><section><QueryBoundary data={list.data?.items} error={list.error} isLoading={list.isLoading} onRetry={list.refresh} emptyTitle="No lessons proposed" emptyDescription="Run evaluations have not produced any evidence-linked candidate lessons.">{(items) => <><div className="os-table-wrap"><table className="os-data-table"><thead><tr><th>Lesson</th><th>Status</th><th>Evidence</th><th>Used</th><th>Updated</th></tr></thead><tbody>{items.map((lesson) => <tr key={lesson.id} className={lesson.id === selectedId ? "is-selected" : undefined}><th scope="row"><AppLink href={`/learning/lessons/${encodeURIComponent(lesson.id)}`}>{lesson.statement}</AppLink><small>{lesson.lessonType} · {lesson.applicabilityScope}</small></th><td><StatusPill status={lesson.status} /></td><td>{lesson.supportingEvidenceCount}/{lesson.evidenceCount}</td><td>{lesson.usageCount}</td><td>{formatTime(lesson.updatedAt)}</td></tr>)}</tbody></table></div><CursorControls cursor={filters.values.cursor} nextCursor={list.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary></section><aside className="os-detail-panel"><LessonDetail item={detail.data} loading={detail.isLoading && Boolean(selectedId)} error={detail.error} onRetry={detail.refresh} onChanged={() => { detail.refresh(); list.refresh(); }} /></aside></div></>;
}

function LessonDetail({ item, loading, error, onRetry, onChanged }: { item?: LessonRecord; loading: boolean; error?: Error; onRetry: () => void; onChanged: () => void }) {
  const [status, setStatus] = useState("under_review"); const [reason, setReason] = useState(""); const action = useActionState();
  if (loading) return <LoadingPanel label="Loading lesson provenance" />; if (error && !item) return <ErrorPanel error={error} onRetry={onRetry} />; if (!item) return <Card><p className="os-muted">Select a lesson to inspect its evidence, risks, provenance, and review history.</p></Card>;
  const submit = (event: FormEvent) => { event.preventDefault(); void action.run(() => operationsApi.reviewLesson(item.id, { expectedUpdatedAt: item.updatedAt, status, reason }, `lesson-${crypto.randomUUID()}`).then(onChanged), "Lesson review recorded."); };
  return <Card><div className="os-card-heading"><h2>{item.statement}</h2><StatusPill status={item.status} /></div><p>{item.expectedBenefit}</p><KeyValueGrid items={[{ label: "Confidence", value: percent(item.confidence) }, { label: "Evidence support", value: `${item.supportingEvidenceCount}/${item.evidenceCount}` }, { label: "Usage", value: item.usageCount }, { label: "Author", value: item.authoringAgentId ?? "System" }]} />{item.failureCategory && <p><strong>Failed-attempt category:</strong> {item.failureCategory}</p>}{item.retryConditions && <p><strong>Retry only when:</strong> {item.retryConditions}</p>}<h3>Supporting evidence</h3>{item.evidence?.length ? <ul className="os-compact-list">{item.evidence.map((link, index) => <li key={`${link.evidenceId ?? link.runId}:${index}`}><span>{link.evidenceSummary ?? link.rationale}</span><StatusPill status={link.relationship} /></li>)}</ul> : <p className="os-muted">No evidence details returned. Verification remains blocked without support.</p>}
    <form className="os-review-form" onSubmit={submit}><h3>Independent review</h3><label><span>Decision</span><select value={status} onChange={(event) => setStatus(event.target.value)}>{["under_review", "verified", "rejected", "stale", "superseded"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Reason</span><textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label>{action.error && <ErrorPanel error={action.error} />}{action.message && <p role="status" className="os-success-note">{action.message}</p>}<Button disabled={action.pending || reason.trim().length < 3}>{action.pending ? "Recording…" : "Record review"}</Button></form></Card>;
}

function Evaluations({ filters }: { filters: ReturnType<typeof useUrlFilters> }) {
  const query = useQuery(`evaluations:${filters.key}`, (signal) => operationsApi.evaluations(filters.values, signal));
  return <><div className="os-filter-bar"><SelectFilter filters={filters} name="journey" label="Journey" options={[{ value: "autonomous", label: "Autonomous" }, { value: "guided", label: "Guided" }]} /></div><QueryBoundary data={query.data?.items} error={query.error} isLoading={query.isLoading} onRetry={query.refresh} emptyTitle="No run evaluations" emptyDescription="Terminal mission runs have not produced evaluation records.">{(items) => <><div className="os-evaluation-grid">{items.map((evaluation) => <Card key={evaluation.id}><div className="os-card-heading"><div><p className="os-eyebrow">{evaluation.journey}</p><h2>{evaluation.mission.name}</h2></div><StatusPill status={evaluation.run.status} /></div><p>{evaluation.retrospective}</p><KeyValueGrid items={[{ label: "Evidence coverage", value: percent(evaluation.evidenceCoverage) }, { label: "Created", value: formatTime(evaluation.createdAt) }]} /><JsonDetails label="Scores and measurements" value={{ scores: evaluation.scores, metrics: evaluation.metrics }} /></Card>)}</div><CursorControls cursor={filters.values.cursor} nextCursor={query.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary></>;
}

function Usage({ filters }: { filters: ReturnType<typeof useUrlFilters> }) {
  const query = useQuery(`lesson-usage:${filters.key}`, (signal) => operationsApi.lessonUsage(filters.values, signal));
  return <QueryBoundary data={query.data?.items} error={query.error} isLoading={query.isLoading} onRetry={query.refresh} emptyTitle="No verified lesson reuse" emptyDescription="No mission has yet recorded selective lesson influence.">{(items) => <><ol className="os-semantic-feed">{items.map((usage) => <li key={usage.id}><div className="os-feed-marker" /><article><header><div><strong>{usage.lesson.statement}</strong><span>{usage.mission.name}</span></div><time>{formatTime(usage.usedAt)}</time></header><p>{usage.influenceSummary}</p>{usage.outcome && <p><strong>Outcome:</strong> {usage.outcome}</p>}<JsonDetails label="Measured impact" value={usage.measuredImpact} /></article></li>)}</ol><CursorControls cursor={filters.values.cursor} nextCursor={query.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary>;
}
