import { operationsApi } from "../../data/api/operations";
import { useQuery } from "../../data/cache/QueryProvider";
import { Card, PageHeader, StatusPill } from "../../design-system/components/Primitives";
import { CursorControls, formatTime, JsonDetails, KeyValueGrid, QueryBoundary, SelectFilter, StreamState, SurfaceTabs, useUrlFilters } from "../runs/OperationalSurface";

type View = "connections" | "policies" | "settings";
export default function SystemPage({ view }: { view: View }) {
  return <div className="os-page"><PageHeader eyebrow="Runtime configuration" title="System" description="Redacted provider, MCP, policy, and health projections from canonical operational state." actions={<StreamState />} />
    <SurfaceTabs current={view} items={[{ id: "connections", label: "Connections", href: "/system/connections" }, { id: "policies", label: "Policies", href: "/system/policies" }, { id: "settings", label: "Settings status", href: "/system/settings" }]} />
    {view === "connections" && <Connections />}{view === "policies" && <Policies />}{view === "settings" && <SettingsStatus />}
  </div>;
}

function Connections() {
  const filters = useUrlFilters({ limit: "25" });
  const providers = useQuery(`system-providers:${filters.values.providerCursor ?? "first"}`, (signal) => operationsApi.providers({ limit: 25, cursor: filters.values.providerCursor }, signal));
  const mcp = useQuery(`system-mcp:${filters.values.mcpCursor ?? "first"}:${filters.values.status ?? "all"}`, (signal) => operationsApi.mcp({ limit: 25, cursor: filters.values.mcpCursor, status: filters.values.status }, signal));
  return <div className="os-section-stack"><section><h2>Providers</h2><QueryBoundary data={providers.data?.items} error={providers.error} isLoading={providers.isLoading} onRetry={providers.refresh} emptyTitle="No provider turns recorded" emptyDescription="Provider health is inferred only from actual durable turn history.">{(items) => <><div className="os-health-grid">{items.map((provider) => <article key={provider.id}><div><strong>{provider.provider}</strong><span>{provider.model ?? "Default model"}</span></div><StatusPill status={provider.status} /><KeyValueGrid items={[{ label: "Turns", value: provider.turnCount }, { label: "Failures", value: provider.failedCount }, { label: "Mean latency", value: provider.meanLatencyMs === null ? "—" : `${Math.round(provider.meanLatencyMs)} ms` }, { label: "Last turn", value: formatTime(provider.lastTurnAt) }]} /></article>)}</div><CursorControls cursor={filters.values.providerCursor} nextCursor={providers.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ providerCursor: cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary></section>
    <section><div className="os-section-heading"><h2>MCP servers</h2><div className="os-inline-filter"><SelectFilter filters={filters} name="status" label="Status" resetKeys={["mcpCursor"]} options={["unknown", "healthy", "degraded", "offline", "quarantined"].map((value) => ({ value, label: value }))} /></div></div><QueryBoundary data={mcp.data?.items} error={mcp.error} isLoading={mcp.isLoading} onRetry={mcp.refresh} emptyTitle="No MCP servers registered" emptyDescription="The registry has not returned any real MCP connection records.">{(items) => <><div className="os-table-wrap"><table className="os-data-table"><thead><tr><th>Server</th><th>Status</th><th>Transport</th><th>Endpoint</th><th>Checked</th></tr></thead><tbody>{items.map((server) => <tr key={server.id}><th scope="row">{server.name}<JsonDetails label="Capabilities and policy" value={{ capabilities: server.capabilities, policy: server.policy }} /></th><td><StatusPill status={server.status} /></td><td>{server.transport}</td><td className="os-mono">{server.endpointRedacted ?? "Hidden"}</td><td>{formatTime(server.lastCheckedAt)}</td></tr>)}</tbody></table></div><CursorControls cursor={filters.values.mcpCursor} nextCursor={mcp.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ mcpCursor: cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary></section></div>;
}

function Policies() {
  const filters = useUrlFilters({ limit: "25" }); const query = useQuery(`system-policies:${filters.key}`, (signal) => operationsApi.policies(filters.values, signal));
  return <QueryBoundary data={query.data?.items} error={query.error} isLoading={query.isLoading} onRetry={query.refresh} emptyTitle="No policy projections" emptyDescription="No authorization, runtime, agent, or MCP policy records are visible in this access scope.">{(items) => <><div className="os-policy-list">{items.map((policy) => <Card key={policy.id}><div className="os-card-heading"><div><p className="os-eyebrow">{policy.sourceType}</p><h2>{policy.label}</h2></div><StatusPill status={policy.sensitivity} /></div><time>{formatTime(policy.updatedAt)}</time><JsonDetails label="Redacted policy document" value={policy.policy} /></Card>)}</div><CursorControls cursor={filters.values.cursor} nextCursor={query.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary>;
}

function SettingsStatus() {
  const filters = useUrlFilters({ limit: "50" }); const health = useQuery(`system-health:${filters.key}`, (signal) => operationsApi.systemHealth(filters.values, signal)); const policies = useQuery("system-settings-policies", (signal) => operationsApi.policies({ limit: 100 }, signal));
  return <><Card className="os-callout"><h2>Configuration is read-only in this API contract</h2><p>Ti-Scale shows the canonical health and policy state below. It will not fabricate editable settings or silently mutate authorization without a versioned settings endpoint.</p><div className="os-page-actions"><a className="os-button os-button--secondary" href="/api/v2/openapi.json" target="_blank" rel="noreferrer">Open API contract</a><a className="os-button os-button--quiet" href="/api/v2/contracts/events" target="_blank" rel="noreferrer">Open event contract</a></div></Card><QueryBoundary data={health.data?.items} error={health.error} isLoading={health.isLoading} onRetry={health.refresh} emptyTitle="No system health data" emptyDescription="No canonical settings-health snapshots have been captured.">{(items) => <div className="os-health-grid">{items.map((item) => <article key={item.id}><div><strong>{item.componentId ?? "System"}</strong><span>{item.componentType ?? "component"}</span></div><StatusPill status={item.status} />{item.message && <p>{item.message}</p>}<time>{formatTime(item.capturedAt)}</time><JsonDetails label="Metrics" value={item.metrics} /></article>)}</div>}</QueryBoundary>{policies.error && <p className="os-muted">Policy count unavailable: {policies.error.message}</p>}{policies.data && <p className="os-muted">{policies.data.items.length} policy projections are currently visible to this operator.</p>}</>;
}
