import { AppLink } from "../../app/router/navigation";
import { operationsApi } from "../../data/api/operations";
import { useQuery } from "../../data/cache/QueryProvider";
import { Card, ErrorPanel, LoadingPanel, PageHeader, StatusPill } from "../../design-system/components/Primitives";
import { CursorControls, FilterForm, formatTime, JsonDetails, KeyValueGrid, QueryBoundary, StreamState, useUrlFilters } from "../runs/OperationalSurface";
import { ContextUsedDisclosure } from "../brain/ContextUsedDisclosure";

export default function ReportsPage({ reportId }: { reportId?: string }) {
  const filters = useUrlFilters({ limit: "25" });
  const list = useQuery(`reports:${filters.key}`, (signal) => operationsApi.reports(filters.values, signal));
  const detail = useQuery(`report:${reportId ?? "none"}`, (signal) => reportId ? operationsApi.report(reportId, signal) : Promise.resolve(undefined));
  return <div className="os-page"><PageHeader eyebrow="Mission deliverables" title="Reports" description="Durable report artifacts, hashes, evidence coverage, and safe storage availability." actions={<StreamState />} />
    <FilterForm filters={filters} searchKey="missionId" searchLabel="Mission ID" />
    <div className="os-master-detail"><section aria-label="Report records"><QueryBoundary data={list.data?.items} error={list.error} isLoading={list.isLoading} onRetry={list.refresh} emptyTitle="No reports generated" emptyDescription="Mission completion has not produced a report artifact in this scope.">{(items) => <><div className="os-table-wrap"><table className="os-data-table"><thead><tr><th>Report</th><th>Mission</th><th>Coverage</th><th>Size</th><th>Created</th></tr></thead><tbody>{items.map((report) => <tr key={report.id} className={report.id === reportId ? "is-selected" : undefined}><th scope="row"><AppLink href={`/reports/${encodeURIComponent(report.id)}`} aria-label={`Open report ${report.artifactType} (${report.id})`}>{report.artifactType}</AppLink><small>{report.mediaType}</small></th><td>{report.mission.name}</td><td>{report.evaluation?.evidenceCoverage === null || report.evaluation === null ? "—" : `${Math.round(report.evaluation.evidenceCoverage * 100)}%`}</td><td>{report.byteSize.toLocaleString()} B</td><td>{formatTime(report.createdAt)}</td></tr>)}</tbody></table></div><CursorControls context="reports" cursor={filters.values.cursor} nextCursor={list.data?.nextCursor ?? null} onChange={(cursor) => filters.set({ cursor }, { resetCursor: false, replace: false })} /></>}</QueryBoundary></section>
      <aside className="os-detail-panel">{reportId && detail.isLoading && <LoadingPanel label="Loading report metadata" />}{reportId && detail.error && !detail.data && <ErrorPanel error={detail.error} onRetry={detail.refresh} />}{!reportId && <Card><p className="os-muted">Select a report to inspect its immutable hash, evidence coverage, and export readiness.</p></Card>}{detail.data && <Card><div className="os-card-heading"><div><p className="os-eyebrow">{detail.data.mission.name}</p><h2>{detail.data.artifactType}</h2></div><StatusPill status={detail.data.storage.available ? "available" : "unavailable"} /></div><KeyValueGrid items={[{ label: "Journey", value: detail.data.journey === "autonomous" ? "Autonomous" : "Guided" }, { label: "Media", value: detail.data.mediaType }, { label: "Size", value: `${detail.data.byteSize.toLocaleString()} bytes` }, { label: "Sensitivity", value: detail.data.sensitivity }, { label: "Evidence coverage", value: detail.data.evaluation?.evidenceCoverage === null || !detail.data.evaluation ? "Not evaluated" : `${Math.round(detail.data.evaluation.evidenceCoverage * 100)}%` }, { label: "Hash", value: <span className="os-mono">{detail.data.contentHash}</span> }]} />{detail.data.contextPackIds.length > 0 ? <section aria-label="Report memory context"><p className="os-eyebrow">Memory transparency</p>{detail.data.contextPackIds.map((packId) => <ContextUsedDisclosure key={packId} packId={packId} />)}</section> : <p className="os-muted">No memory context pack is linked to this report’s producing action.</p>}<JsonDetails label="Report metadata" value={detail.data.metadata} /><p className="os-muted">The API exposes a redacted storage projection only. Direct download requires a separate authorized artifact-delivery contract.</p></Card>}</aside>
    </div>
  </div>;
}
